//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardDetail()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public string CardID { get; set; }
        public System.DateTime Validity { get; set; }
        public string CardType { get; set; }
        public bool ActivationStatus { get; set; }
        public Nullable<int> TotalCredit { get; set; }
        public Nullable<int> RemainingCredit { get; set; }
        public Nullable<bool> EMIPendingStatus { get; set; }
        public Nullable<int> CustomerID { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
    }
}
