//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int PurchaseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string CardID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> EmiScheme { get; set; }
        public Nullable<double> EmiPerMonth { get; set; }
        public Nullable<double> EmiPaid { get; set; }
        public Nullable<double> EmiLeft { get; set; }
        public virtual CardDetail CardDetail { get; set; }
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
